In [2]:
import numpy as np

In [3]:
def generate_code(k, n):
    code = 2*np.around(np.random.rand(k, n)) - 1
    code = code.astype(int)
    return code

In [4]:
code = generate_code(3, 4)
print(code)

[[-1 -1  1 -1]
 [-1  1  1 -1]
 [ 1 -1  1 -1]]


In [5]:
def encode(code, messages):
    message_diag = np.diag(messages)
    return np.dot(message_diag, code)

In [6]:
codewords = encode(code, [1, -1, -1])
print(codewords)

[[-1 -1  1 -1]
 [ 1 -1 -1  1]
 [-1  1 -1  1]]


In [7]:
def receive(codewords):
    return np.sum(codewords, axis=0)

In [7]:
y = receive(codewords)
print(y)

[-1  1  1  3]


In [8]:
def decode(code, y):           # return all the decoded codewords, solution to homework problem
    return np.sign(np.dot(y, np.matrix.transpose(code)))

In [9]:
decoded_messages = decode(code, y)
print(decoded_messages)

[ 1 -1  0]


In [24]:
def error_probability():      # part of solution
    P = []
    for m in range(0, 10000):
        code = generate_code(50, 100)
        messages = np.random.choice([1,-1],50)
        codewords = encode(code, messages)
        y = receive(codewords)
        decoded_messages = decode(code, y)
        P_err = np.count_nonzero(decoded_messages - messages)/50
        P.append(P_err)
    return sum(P)/10000

In [25]:
error_probability()

0.07857799999999904