<font size="4" style="color:red;"> **IMPORTANT: ** When submitting this homework notebook, please modify only cells that start with:</font>

```python
# modify this cell
```

## Setup Notebook

**Note:** Read the communications notebooks before attempting this homework.

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## Helper Code

The following code will be used in generating questions.

In [12]:
def generate_code(k, n):
    code = 2*np.around(np.random.rand(k, n)) - 1
    code = code.astype(int)
    return code

def encode(code, messages):
    message_diag = np.diag(messages)
    return np.dot(message_diag, code)

def receive(codewords):
    return np.sum(codewords, axis=0)

# Problem 1

Write a function **decode** that takes a codeword matrix $C$, a received vector $y$, and outputs the decoded message.

<font  style="color:blue"> **Code:**</font>
```python
random.seed(0)
code = generate_code(3, 4)
print"generated code:";print(code)

codewords = encode(code, [1, -1, -1])
print;print "code words:"; print(codewords)

message = receive(codewords)
print;print "received message"; print(message)

decoded_message = decode(codewords, message)
print; print "decoded message:",decoded_message
print "decoded message type: ",type(decoded_message);
```


<font  style="color:magenta"> **Output**</font>
```
generated code:
[[ 1  1  1  1]
 [-1  1 -1  1]
 [ 1 -1  1  1]]

code words:
[[ 1  1  1  1]
 [ 1 -1  1 -1]
 [-1  1 -1 -1]]

received message
[ 1  1  1 -1]

decoded message: [ 1 -1  0]
decoded message type:  <type 'numpy.ndarray'>
```

In [14]:
# modify this cell

def decode(C, y):
    # input: y is a 1D numpy.ndarray, C is a 2D numpy.ndarray
    # output: a numpy array of integers
    
    ### BEGIN SOLUTION
    return np.sign(np.dot(y, np.matrix.transpose(code)))
    ### END SOLUTION


In [24]:
# Check Function
random.seed(1)
code = generate_code(4, 5)
message = array(1,1,-1,-1,1)
decode(code, message)

#assert (# please complete this)

### BEGIN HIDDEN TESTS
# please complete this
### END HIDDEN TESTS

ValueError: only 2 non-keyword arguments accepted

## Problem 2

Write a function, **error_probability** that simulates communication between $50$ senders and $1$ receiver. It generates a $50\times100$ random codeword matrix $C$ whose entries are i.i.d. uniform over $\{-1,1\}$, $50$ i.i.d. random messages uniformly distributed over $\{-1, 1\}$, and encodes the messages using the matrix $C$. It then computes the sum of all  encoded messages and stores them as the received codeword vector $y$. It then invokes the function you wrote in Problem 1 above to decode the messages (for every $i$ in $\{1,2,\ldots,50\}$). Finally, it calculates the fraction of wrongly decoded messages (by comparison with the original messages that were sent). The entire sequence of steps must be performed $10,000$ times and the function returns the mean fraction of wrongly decoded messages.

<font  style="color:blue"> * **Code:** *</font>
```python
print(error_probability())
```


<font  style="color:magenta"> * **Output:** *</font>
```
0.162
<type 'float'>
```

In [ ]:
# modify this cell

def error_probability():
    ### BEGIN SOLUTION
    P = []
    for m in range(0, 10000):
        code = generate_code(50, 100)
        messages = np.random.choice([1,-1],50)
        codewords = encode(code, messages)
        y = receive(codewords)
        decoded_messages = decode(code, y)
        P_err = np.count_nonzero(decoded_messages - messages)/50.0
        P.append(P_err)
    return sum(P)/10000.0    
    ### END SOLUTION

# modify this cell

In [ ]:
# Check Function

assert (# please complete this)

### BEGIN HIDDEN TESTS
# please complete this
### END HIDDEN TESTS