In [3]:
import random
random.randrange?

In [12]:
%%writefile ExpectationScaling.imd
#### Written by Yoav Freund 11/3/2016

```python
# random variables (no need to import random library)
def rand_vals(i=1,j=100,n=3):
    return [random.randrange(i,j,1) for k in range(n)]
a_rand=rand_vals() ; b_rand=rand_vals(n=2)
a_vals=[]; b_vals=[];
for i in range(len(a_rand)):
    for j in range(len(b_rand)):
        a_vals.append(a_rand[i])
        b_vals.append(b_rand[j])
variable_values = {'a':a_vals, 'b':b_vals}
print variable_values
# Random valued coefficients:
[c,d,e,f,g]=rand_vals(i=1,j=4,n=5)

#index_of_test_value = 2 #should not be used.
# Solutions with variables converted to string
# Make sure you name the solution with part id at the end. e.g. 'solution1' will be solution for part 1. 
solution1 = "{0}*a".format(c)
solution2 = "{0}*a+{1}*b+{2}".format(c,d,e)
solution3 = "-{0}*a+{1}*b+{2}*{3}*v-1".format(c,d,c,d) 

# Group all solutions into a list
solutions = [solution1, solution2, solution3]
solutions
```

# Expectation calculations

Suppose $X,Y$ are random variables and that $a=E(X), b=E(Y), v=E(XY)$ 

Express the following using $a$ and $b$

1. $E(\c X)$

[_]

2. $E(\c*X+ \d*Y+\e)$

[_]

3. $E((\c*X+1)*(\d*Y-1))$

[_]

Overwriting ExpectationScaling.imd


In [7]:
#%%writefile ExpectationVarianceScaling.imd
#### Written by Yoav Freund 11/3/2016

#```python
# random variables (no need to import random library)
def rand_vals(i=1,j=100,n=3):
    return [random.randrange(i,j,1) for k in range(n)]
a_rand=rand_vals() ; b_rand=rand_vals(n=2)
a_vals=[]; b_vals=[];
for i in range(len(a_rand)):
    for j in range(len(b_rand)):
        a_vals.append(a_rand[i])
        b_vals.append(b_rand[j])
variable_values = {'a':a_vals, 'b':b_vals}
# Random valued coefficients:
[c,d,e]=rand_vals(i=2,j=8,n=3)

#index_of_test_value = 2 #should not be used.
# Solutions with variables converted to string
# Make sure you name the solution with part id at the end. e.g. 'solution1' will be solution for part 1. 
solution1 = "{0}*a-{0}*a".format(c)
solution2 = "{0}*a-{0}*a".format(c)
solution3 = "{0}*a-{1}*a".format(c,d)
solution4 = "({0}**2)*b".format(c)
solution5 = "2*({0}**2)*b".format(c,d)
solution6 = "0"

# Group all solutions into a list
solutions = [solution1, solution2, solution3, solution4, solution5, solution6]
solutions
#```

['2*a-2*a', '2*a-2*a', '2*a-2*a', '(2**2)*b', '2*(2**2)*b', '0']

# Expectation and Variance Calculations

Suppose $X_1,X_2$ are independent and identically distributed random variables 
such that $a=E(X_1)=E(X_2)$ , $b^2=Var(X)$ 

Express the following using $a$ and $b$:

1. $E(\c X_1 - \c X_2)$

[_]

2. $E(\c X_1 - \c X_1)$

[_]

3. $E(\c X_1 - \d X_1)$

[_]

4. $Var(\c X_1 + \e)$

[_]

5. $Var(\c X_1 - \c X_2)$

[_]

6. $Var(\c X_1 - \c X_1)$

[_]

In [9]:
#%%writefile Covariance.imd
#### Written by Yoav Freund 11/3/2016
#```python

# Solutions with variables converted to string
# Make sure you name the solution with part id at the end. e.g. 'solution1' will be solution for part 1. 

import numpy as np

X_vals=np.array([1.,2.,3.])
Y_vals=np.array([1.,2.,3.])

# this imd can generate a number of different problems, each for a different matrix
# the matrices are specified here:

matrices={'dep_corr1':np.array([[1./3,0,0],[0,1./3,0],[0,0,1./3]]),
          'indep_uncor': np.array([[.1,0,.4],[0,0,0],[.1,0,.4]]),
          'dep_uncor': np.array([[.2,0,.2],[0,.2,0],[.2,0,.2]])
          }

joint=matrices['dep_uncor']
print joint[0,2]
marginal_X=np.sum(joint,axis=0)
marginal_Y=np.sum(joint,axis=1)
print marginal_X, marginal_Y
mean_X=np.dot(marginal_X,X_vals)
mean_Y=np.dot(marginal_Y,Y_vals)

X_Nvals=X_vals-mean_X
Y_Nvals=Y_vals-mean_Y

var_X=np.dot(marginal_X,X_Nvals**2)
var_Y=np.dot(marginal_Y,Y_Nvals**2)

print var_X,var_Y

xy=np.outer(X_vals,Y_vals)
Nxy=np.outer(X_Nvals,Y_Nvals)
print Nxy

Cov = np.sum(np.multiply(Nxy,joint))
Exy = np.sum(np.multiply(xy,joint))

print Exy, Cov, Cov/np.sqrt(var_X*var_Y)
independent=np.sum(np.outer(marginal_Y,marginal_X)-joint)==0
print independent

# Dist of X
solution1="+".join([str(p) for p in joint[:,0]])
solution2="+".join([str(p) for p in joint[:,1]])
solution3="+".join([str(p) for p in joint[:,2]])
solution4="+".join(["(%.2f*%.2f)"%(marginal_X[i],X_vals[i]) for i in range(len(X_vals))])
solution5="+".join(["(%.2f*(%.2f**2))"%(marginal_X[i],X_Nvals[i]) for i in range(len(X_vals))])
# Dist of Y
solution6="+".join([str(p) for p in joint[0,:]])
solution7="+".join([str(p) for p in joint[1,:]])
solution8="+".join([str(p) for p in joint[2,:]])
solution9="+".join(["(%.2f*%.2f)"%(marginal_Y[i],Y_vals[i]) for i in range(len(Y_vals))])
solution10="+".join(["(%.2f*(%.2f**2))"%(marginal_Y[i],Y_Nvals[i]) for i in range(len(Y_vals))])
#Interactions between X and Y
flat_xy=xy.flatten()
flat_joint=joint.flatten()
solution11="+".join(["(%.2f*%.2f)"%(flat_joint[i],flat_xy[i]) for i in range(len(flat_xy))])
solution12="{0}-({1}*{2})".format(Exy,mean_X,mean_Y)
solution13="{0}/sqrt({1}*{2})".format(Cov,var_X,var_Y)
solution14=1*independent
solutions=[solution1,solution2,solution3,solution4,solution5,solution6,solution7,solution8,
           solution9,solution10,solution11,solution12,solution13,solution14]
solutions
#```

0.2
[ 0.4  0.2  0.4] [ 0.4  0.2  0.4]
0.8 0.8
[[ 1. -0. -1.]
 [-0.  0.  0.]
 [-1.  0.  1.]]
4.0 0.0 0.0
False


['0.2+0.0+0.2',
 '0.0+0.2+0.0',
 '0.2+0.0+0.2',
 '(0.40*1.00)+(0.20*2.00)+(0.40*3.00)',
 '(0.40*(-1.00**2))+(0.20*(0.00**2))+(0.40*(1.00**2))',
 '0.2+0.0+0.2',
 '0.0+0.2+0.0',
 '0.2+0.0+0.2',
 '(0.40*1.00)+(0.20*2.00)+(0.40*3.00)',
 '(0.40*(-1.00**2))+(0.20*(0.00**2))+(0.40*(1.00**2))',
 '(0.20*1.00)+(0.00*2.00)+(0.20*3.00)+(0.00*2.00)+(0.20*4.00)+(0.00*6.00)+(0.20*3.00)+(0.00*6.00)+(0.20*9.00)',
 '4.0-(2.0*2.0)',
 '0.0/sqrt(0.8*0.8)',
 0]

<h1>Covariance Calculations 1 </h1>

<p>&nbsp;</p>

<p>Suppose X,Y are discrete random variables whose joint distribution is&nbsp;</p>

<table align="center" border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<caption>Joint probabilities</caption>
	<thead>
		<tr>
			<th scope="row">&nbsp;</th>
			<th scope="col" style="text-align: center; vertical-align: bottom;">x=1</th>
			<th scope="col" style="text-align: center; vertical-align: bottom;">x=2</th>
			<th scope="col" style="text-align: center; vertical-align: bottom;">x=3</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th scope="row" style="text-align:center; vertical-align:bottom">y=1</th>
			<td style="text-align:center; vertical-align:bottom">\{joint[0,0]}</td>
			<td style="text-align:center; vertical-align:bottom">\{joint[0,1]}</td>
			<td style="text-align:center; vertical-align:bottom">\{joint[0,2]}</td>
		</tr>
		<tr>
			<th scope="row" style="text-align:center; vertical-align:bottom">y=2</th>
			<td style="text-align:center; vertical-align:bottom">\{joint[1,0]}</td>
			<td style="text-align:center; vertical-align:bottom">\{joint[1,1]}</td>
			<td style="text-align:center; vertical-align:bottom">\{joint[1,2]}</td>
		</tr>
		<tr>
			<th scope="row" style="text-align:center; vertical-align:bottom">y=3</th>
			<td style="text-align:center; vertical-align:bottom">\{joint[2,0]}</td>
			<td style="text-align:center; vertical-align:bottom">\{joint[2,1]}</td>
			<td style="text-align:center; vertical-align:bottom">\{joint[2,2]}</td>
		</tr>
	</tbody>
</table>

### What is the distribution over $X$?

$P(X=1)=$

[_]

$P(X=2)=$

[_]

$P(X=3)=$

[_]


What is $E(X)$ ?

[_]

What is $Var(X)$ ?

[_]


### What is the distribution over $Y$?

$P(Y=1)=$

[_]

$P(Y=2)=$

[_]

$P(Y=3)=$

[_]

What is $E(Y)$ ?

[_]

What is $Var(Y)$ ?

[_]

### What is the relationship between $X$ and $Y$ ?

What is $E(XY)$ ?

[_]

What is $Cov(X,Y)$ ?

[_]

What is $Corr(X,Y)$ ?

[_]

Are $X$ and $Y$ independent (1=independent, 0=dependent)?

[_]