In [16]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


## Compute statistics for a known distribution

Requested additions:
1. Do the same calcs for a sample.
2. Show how to do the calcs without .dot and outer, just standard python (much slower, but ok).
3. Add text to explain each step

### Define a joint distribution over two discrete random variables
The probabilities are organized in a 2D array, where the columns correspond to $x$ and the rows correspond to $y$

In [75]:
P=np.array([[1.,1,2],[1,1,2]])
P/=sum(P)
P

array([[ 0.125,  0.125,  0.25 ],
       [ 0.125,  0.125,  0.25 ]])

In [76]:
x=np.array([1,2,3])
y=np.array([-1,1])

In [77]:
Px=sum(P,axis=0)
Py=sum(P,axis=1)
Px,Py

(array([ 0.25,  0.25,  0.5 ]), array([ 0.5,  0.5]))

### Check whether $x$ and $y$ are independent

If they are independent then the outer product and P should be equal.

In [78]:
np.outer(Px,Py).T - P

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### Subtract the means

In [79]:
from math import sqrt
Ex=np.dot(Px,x)
Ey=np.dot(Py,y)
Ex2=np.dot(Px,x**2)
Ey2=np.dot(Py,y**2)
stdx=sqrt(Ex2-Ex**2)
stdy=sqrt(Ey2-Ey**2)
Ex,Ey,stdx,stdy


(2.25, 0.0, 0.82915619758885, 1.0)

In [80]:
nx=x-Ex
nx

array([-1.25, -0.25,  0.75])

In [81]:
ny=y-Ey
ny

array([-1.,  1.])

### Calculate the covariance


In [82]:
s=0
for i in range(len(x)):
    for j in range(len(y)):
        s+=P[j,i]*nx[i]*ny[j]
print 'the covariance is',s

the covariance is 0.0


### and the correlation


## Empirical statistics
Repeat the calculation above by sampling from the joint distribution and calculating the emprical expectations, variance and covariance

Use sums over the sample, not over the elements of the space.