In [2]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


## Compute statistics for a known distribution

Requested additions:
1. Do the same calcs for a sample.
2. Show how to do the calcs without .dot and outer, just standard python (much slower, but ok).
3. Add text to explain each step

### Defining a joint distribution over two discrete random variables
The probabilities are organized in a 2D array, where the columns correspond to values of $x$ and the rows correspond to values of $y$

In [10]:
# We start with positive weights that don't sum to 1
P=np.array([[1.,1,2],[1,2,1]])
P2=copy(P)
P

array([[ 1.,  1.,  2.],
       [ 1.,  2.,  1.]])

In [11]:
# We then normalize the weights
# using Pure Python

#Compute the sum
s=0
for i in range(shape(P)[0]):
    for j in range(shape(P)[1]):
        s+=P[i,j]
print 'the sum is ',s
#divide by the sum
for i in range(shape(P)[0]):
    for j in range(shape(P)[1]):
        P[i,j] /= s
P

the sum is  8.0


array([[ 0.125,  0.125,  0.25 ],
       [ 0.125,  0.25 ,  0.125]])

In [13]:
# Using Numpy we can write it in a much shorter way
P2/=sum(P2)
P2

array([[ 0.125,  0.125,  0.25 ],
       [ 0.125,  0.25 ,  0.125]])

In [5]:
# The values that the random variables x and y take
x=np.array([1,2,3])
y=np.array([-1,1])

#### Computing Marginals
The marginal distributions are the probabilities associated with each random variable alone.

In [22]:
# The python way
Px=[0]*shape(P)[1]
Py=[0]*shape(P)[0]
for i in range(shape(P)[0]):
    for j in range(shape(P)[1]):
        Px

In [86]:
#the numpy way:
Px=sum(P,axis=0)
Py=sum(P,axis=1)
Px,Py

(array([ 0.25 ,  0.375,  0.375]), array([ 0.5,  0.5]))

### Check whether $x$ and $y$ are independent

If they are independent then the outer product and P should be equal.

In [87]:
np.outer(Px,Py).T - P

array([[ 0.    ,  0.0625, -0.0625],
       [ 0.    , -0.0625,  0.0625]])

### Subtract the means

In [88]:
from math import sqrt
Ex=np.dot(Px,x)
Ey=np.dot(Py,y)
Ex2=np.dot(Px,x**2)
Ey2=np.dot(Py,y**2)
stdx=sqrt(Ex2-Ex**2)
stdy=sqrt(Ey2-Ey**2)
Ex,Ey,stdx,stdy


(2.125, 0.0, 0.7806247497997998, 1.0)

In [89]:
nx=x-Ex
nx

array([-1.125, -0.125,  0.875])

In [90]:
ny=y-Ey
ny

array([-1.,  1.])

### Calculate the covariance


In [91]:
s=0
for i in range(len(x)):
    for j in range(len(y)):
        s+=P[j,i]*nx[i]*ny[j]
print 'the covariance is',s

the covariance is -0.125


### and the correlation


## Empirical statistics
Repeat the calculation above by sampling from the joint distribution and calculating the emprical expectations, variance and covariance

Use sums over the sample, not over the elements of the space.