In [1]:
import numpy as np

In [2]:
def generate_code(k, n):
    code = 2*np.around(np.random.rand(k, n)) - 1
    code = code.astype(int)
    return code

In [3]:
code = generate_code(3, 4)
print(code)

[[ 1  1 -1 -1]
 [ 1 -1  1  1]
 [ 1  1 -1  1]]


In [4]:
def encode(code, messages):
    message_diag = np.diag(messages)
    return np.dot(message_diag, code)

In [5]:
codewords = encode(code, [1, -1, -1])
print(codewords)

[[ 1  1 -1 -1]
 [-1  1 -1 -1]
 [-1 -1  1 -1]]


In [6]:
def receive(codewords):
    return np.sum(codewords, axis=0)

In [7]:
y = receive(codewords)
print(y)

[-1  1 -1 -3]


In [8]:
def decode(y, code):
    return np.sign(np.dot(y, np.matrix.transpose(code)))

In [9]:
decoded_messages = decode(y, code)
print(decoded_messages)

[ 1 -1 -1]


In [10]:
def simulate(k, n):
    code = generate_code(k, n)
    messages = np.random.choice([1,-1],k)
    codewords = encode(code, messages)
    y = receive(codewords)
    decoded_messages = decode(y, code)
    P_err = np.count_nonzero(decoded_messages - messages)/k
    return P_err

In [11]:
simulate(50, 100)

0.14

In [20]:
P = []
for m in range(0, 10000):
    P.append(simulate(50, 100))
sum(P)/10000

0.0786179999999992