In [1]:
import numpy as np
import itertools

In [2]:
def generate_code(k, n):
    code = np.random.randint(2, size=(k,n))
    return code

In [3]:
def hamming_distance(u, v):
    codeword_sum = np.mod(u+v, 2)
    h = (codeword_sum != 0).sum(1)
    return np.asarray(h)

In [4]:
code = generate_code(3, 4)
type(code[0][0])

numpy.int32

In [5]:
def closeness_probability(k, n):
    code = generate_code(k, n)
    choose_2 = list(itertools.combinations(code, 2))
    u, v = np.matrix([x[0] for x in choose_2]), np.matrix([x[1] for x in choose_2])
    h = hamming_distance(u, v)
    return len(h[h<=n/3])/len(h)

In [69]:
P = []
for i in range(0, 1000):
    P.append(closeness_probability(50, 100))
sum(P)/1000

0.00044571428571428827

In [7]:
def encode(code, messages):
    message_diag = np.diag(messages)
    return np.dot(message_diag, code)

In [8]:
len(np.mod([2, 0, 0, 1, 2, 1], 2))

6

In [9]:
'''
import time
start_time = time.time()
for i in range(0, 500):
    for j in range(0, 500):
        hamming_distance(code[i], code[j])
print("--- %s seconds ---" % (time.time() - start_time))
'''

'\nimport time\nstart_time = time.time()\nfor i in range(0, 500):\n    for j in range(0, 500):\n        hamming_distance(code[i], code[j])\nprint("--- %s seconds ---" % (time.time() - start_time))\n'

In [10]:
'''
import time
start_time = time.time()
choose_2 = list(itertools.combinations(code, 2))
for x in choose_2:
    ()
print("--- %s seconds ---" % (time.time() - start_time))
'''

'\nimport time\nstart_time = time.time()\nchoose_2 = list(itertools.combinations(code, 2))\nfor x in choose_2:\n    ()\nprint("--- %s seconds ---" % (time.time() - start_time))\n'

In [11]:
code = np.matrix(generate_code(500, 1000))

In [12]:
import math

In [13]:
1 - math.erf(17/(5*(2**0.5)))

0.0006738585313537104

In [14]:
8.44/0.072

117.22222222222223

In [47]:
from scipy.stats import binom
n0 = 100
k0 = np.arange(0, 101)
P_binom = binom.pmf(k0, n0, 0.5)
print(sum(P_binom[0:34]))

0.000436859918456


In [16]:
code = np.around(np.random.rand(1000, 1000))

In [17]:
np.count_nonzero(code)/len(code)**2

0.500766

In [18]:
code = generate_code(6, 6)
print("Code:\n", code)
choose_2 = list(itertools.combinations(code, 2))
print("\n2-combinations:\n", choose_2)
u, v = np.matrix([x[0] for x in choose_2]), np.matrix([x[1] for x in choose_2])
print("\nu, v\n", u, "\n\n", v)
h = hamming_distance(u, v)
print("\nh:\n", np.transpose(h), type(h))
print("\n", (h[h<=6/3]))
print("\n", len(h[h<=6/3])/len(h))

Code:
 [[0 0 1 0 0 0]
 [0 1 0 0 1 1]
 [0 1 0 0 1 0]
 [0 0 0 0 0 1]
 [1 1 1 0 0 1]
 [0 1 1 1 0 1]]

2-combinations:
 [(array([0, 0, 1, 0, 0, 0]), array([0, 1, 0, 0, 1, 1])), (array([0, 0, 1, 0, 0, 0]), array([0, 1, 0, 0, 1, 0])), (array([0, 0, 1, 0, 0, 0]), array([0, 0, 0, 0, 0, 1])), (array([0, 0, 1, 0, 0, 0]), array([1, 1, 1, 0, 0, 1])), (array([0, 0, 1, 0, 0, 0]), array([0, 1, 1, 1, 0, 1])), (array([0, 1, 0, 0, 1, 1]), array([0, 1, 0, 0, 1, 0])), (array([0, 1, 0, 0, 1, 1]), array([0, 0, 0, 0, 0, 1])), (array([0, 1, 0, 0, 1, 1]), array([1, 1, 1, 0, 0, 1])), (array([0, 1, 0, 0, 1, 1]), array([0, 1, 1, 1, 0, 1])), (array([0, 1, 0, 0, 1, 0]), array([0, 0, 0, 0, 0, 1])), (array([0, 1, 0, 0, 1, 0]), array([1, 1, 1, 0, 0, 1])), (array([0, 1, 0, 0, 1, 0]), array([0, 1, 1, 1, 0, 1])), (array([0, 0, 0, 0, 0, 1]), array([1, 1, 1, 0, 0, 1])), (array([0, 0, 0, 0, 0, 1]), array([0, 1, 1, 1, 0, 1])), (array([1, 1, 1, 0, 0, 1]), array([0, 1, 1, 1, 0, 1]))]

u, v
 [[0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 

In [19]:
b = np.asarray(h) 
# b = b.reshape(-1, len(b)) 
b = np.asarray(h).reshape(len(h))
b

array([4, 3, 2, 3, 3, 1, 2, 3, 3, 3, 4, 4, 3, 3, 2])

In [20]:
print(list2d)

NameError: name 'list2d' is not defined

In [21]:
4/15

0.26666666666666666