<font face="Calibri" size="18px" ><strong> HW_2 </strong></font>

<font size="4" style="color:red;"> **IMPORTANT: ** When submitting this homework notebook, please modify only the cells that start with:</font>

```python
# modify this cell
```

## Setup Notebook

We import useful packages and load in the dataset

In [58]:
%matplotlib inline
%run helper.ipynb
import numpy as np
import matplotlib.pyplot as plt
from inspect import getsource
from scipy.stats import norm, multivariate_normal # module for dealing with the Gaussians

The object 'helper' has been imported into this notebook.


In [59]:
# installing packages for interactive graphs
import ipywidgets as widgets
from IPython.display import display
from ipywidgets import interact, interactive, fixed, interact_manual, IntSlider

For this HW we will be examining the famouse Fischer's iris dataset. The dataset uses 4 features of a plant to categorize it into one of 3 species $[1,2,3]$ for our purposes.

We load in the iris test and training data.
The dataset consists of 130 training points and 48 test points.
There are 13 features and a label with one of the values, (0,1,2).

* **x :** an `np.array` of the 120 training points' features.
* **y :** an `np.array` of the 120 training labels.
* **tx :** an `np.array` of the 30 test points' features.
* **ty :** an `np.array` of the 30 test points' labels.

In [60]:
x,y,tx,ty = helper.hw.x, helper.hw.y, helper.hw.tx, helper.hw.ty
print "x.shape :",x.shape
print "tx.shape :",tx.shape
print "y.shape :",y.shape
print "ty.shape :",ty.shape

featurenames = helper.hw.featurenames
print;print "Names of Features:"; print featurenames

x.shape : (120, 4)
tx.shape : (30, 4)
y.shape : (120,)
ty.shape : (30,)

Names of Features:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


## Examining the Dataset

**<font color="red">Important Note: </font>**

For each of the following exercise you are **not** expected to write the solutions from scratch. Please read through the functions in the <font color="blue">helper.ipynb</font> notebook and choose the appropriate function for the problem.

Below we show how the helper functions can be run on the hw's dataset. By plotting some a few graphs of the dataset. Explore these graphs to gain a better understanding of what is the iris dataset.

In [63]:
interact_manual( helper.bi.twoFeaturesPlot,
                f1=IntSlider(0,0,3,1), f2=IntSlider(2,0,3,1), label=IntSlider(1,0,2,1) )

<function __main__.twoFeaturesPlot>

# Exercise 1

Write a function, **feature_moments**, that returns the mean and variance of a given feature. The function's input is the feature integer, and the output should be the tuple, $($mean, variance$)$


<font  style="color:blue"> **Code:**</font>
```python
print feature_moments(0)
print feature_moments(1)
```


<font  style="color:magenta"> **Output**</font>
```
(5.895833333333333, 0.7207326388888889)
(3.0541666666666667, 0.17748263888888888)
```

In [21]:
# modify this cell

def feature_moments(feature):
    # inputs: an integer representing the feature number
    # output: a tuple of floats, (mean, variance)
    
    ### BEGIN SOLUTION
    mean, var = helper.bi.fit_gaussian(x,[feature])
    return float(mean), float(var)
    ### END SOLUTION

In [40]:
# Check Function

assert( sum(abs(feature_moments(2) - np.array([3.83, 3.0901]) ))   < 10**-7 )

### BEGIN HIDDEN TESTS
assert( sum(abs(feature_moments(3) - np.array([1.2166666666666666,0.566388888888889]) ))   < 10**-7 )
### END HIDDEN TESTS

# Exercise 2

Write a function, **test_one_feature**, that returns the number of incorrectly guessed test points when predictng the targets with only 1 feature. The function's input is the feature integer, and the output should be the tuple, $($mean, variance$)


<font  style="color:blue"> **Code:**</font>
```python
print feature_moments(0)
print feature_moments(1)
```


<font  style="color:magenta"> **Output**</font>
```
(5.895833333333333, 0.7207326388888889)
(3.0541666666666667, 0.17748263888888888)
```

In [ ]:
# modify this cell

def test_one_feature(feature):
    # inputs: an integer representing the feature number
    # output: a tuple of floats, (mean, variance)
    
    ### BEGIN SOLUTION
    mean, var = helper.bi.fit_gaussian(x,[feature])
    return float(mean), float(var)
    ### END SOLUTION

In [ ]:
# Check Function

assert( sum(abs(feature_moments(2) - np.array([3.83, 3.0901]) ))   < 10**-7 )

### BEGIN HIDDEN TESTS
assert( sum(abs(feature_moments(3) - np.array([1.2166666666666666,0.566388888888889]) ))   < 10**-7 )
### END HIDDEN TESTS

# Exercise 3

Write a function, **test_two_features**, that returns the number of incorrectly guessed test points when predictng the targets with only 1 feature.$

<font  style="color:blue"> **Code:**</font>
```python
print feature_moments(0)
print feature_moments(1)
```


<font  style="color:magenta"> **Output**</font>
```
(5.895833333333333, 0.7207326388888889)
(3.0541666666666667, 0.17748263888888888)
```

In [ ]:
# modify this cell

def feature_moments(feature):
    # inputs: an integer representing the feature number
    # output: a tuple of floats, (mean, variance)
    
    ### BEGIN SOLUTION
    mean, var = helper.bi.fit_gaussian(x,[feature])
    return float(mean), float(var)
    ### END SOLUTION

In [ ]:
# Check Function

assert( sum(abs(feature_moments(2) - np.array([3.83, 3.0901]) ))   < 10**-7 )

### BEGIN HIDDEN TESTS
assert( sum(abs(feature_moments(3) - np.array([1.2166666666666666,0.566388888888889]) ))   < 10**-7 )
### END HIDDEN TESTS

In [51]:
helper.bi.test_model([0,2])

TypeError: test_model() takes exactly 2 arguments (1 given)

In [55]:
helper.uni.fit_generative_model( 3)

(array([ 0.        ,  1.32093023,  2.04615385,         nan]),
 array([ 0.        ,  0.03839913,  0.07325444,         nan]),
 array([ 0.        ,  0.35833333,  0.325     ,  0.        ]))